### PR TITLE
Instructor

### PR DESCRIPTION
**Pull request by shudaniel**
Add column in database that marks a student as unenrolled instead of deleting them.

### CODE REVIEW

**Comment by garethgeorge** [comment]
@shudaniel I think we should have a followup discussion with next class about how leaving courses is handled. The roster student imo should not be marked as disenrolled, I believe the user_id should be set to nil in that case.

The lazy delete should prevent roster_students from being removed, this way assignment and pair data etc is preserved! But it should allow a student to disassociate / reassociate their github account I think.

Anyway pends further discussion and input from @pconrad !

**Comment by garethgeorge** [comment]
Perhaps we can go over this code review in class, I think this code review needs to be mobbed on.

**Comment by shudaniel** [comment]
Cool no problem. Given that Conrad didn't even know the unenroll/re-enroll button existed until yesterday, we kinda just implemented this temporarily until we get a more solid plan. You're right that this should be something we discuss with Conrad directly.

**Comment by garethgeorge** [comment]
Yep :) looks, and I think everything other than that bit I honed in on is correct.

**Comment by shudaniel** [comment]
Conrad said to just merge for testing.

**Pull request merged**
